#include "lenet_cnn_float.h"

// Global CNN buffers and weights
unsigned char REF_IMG[IMG_DEPTH][IMG_HEIGHT][IMG_WIDTH];
float INPUT_NORM[IMG_DEPTH][IMG_HEIGHT][IMG_WIDTH];
float CONV1_KERNEL[CONV1_NBOUTPUT][IMG_DEPTH][CONV1_DIM][CONV1_DIM];
float CONV1_BIAS[CONV1_NBOUTPUT];
float CONV2_KERNEL[CONV2_NBOUTPUT][POOL1_NBOUTPUT][CONV2_DIM][CONV2_DIM];
float CONV2_BIAS[CONV2_NBOUTPUT];
float FC1_KERNEL[FC1_NBOUTPUT][POOL2_NBOUTPUT][POOL2_HEIGHT][POOL2_WIDTH];
float FC1_BIAS[FC1_NBOUTPUT];
float FC2_KERNEL[FC2_NBOUTPUT][FC1_NBOUTPUT];
float FC2_BIAS[FC2_NBOUTPUT];
float FC2_OUTPUT[FC2_NBOUTPUT];
float SOFTMAX_OUTPUT[FC2_NBOUTPUT];