#ifndef GLOBALS_H
#define GLOBALS_H

#include "lenet_cnn_float.h"

extern unsigned char REF_IMG[IMG_DEPTH][IMG_HEIGHT][IMG_WIDTH];
extern float INPUT_NORM[IMG_DEPTH][IMG_HEIGHT][IMG_WIDTH];
extern float CONV1_KERNEL[CONV1_NBOUTPUT][IMG_DEPTH][CONV1_DIM][CONV1_DIM];
extern float CONV1_BIAS[CONV1_NBOUTPUT];
extern float CONV2_KERNEL[CONV2_NBOUTPUT][POOL1_NBOUTPUT][CONV2_DIM][CONV2_DIM];
extern float CONV2_BIAS[CONV2_NBOUTPUT];
extern float FC1_KERNEL[FC1_NBOUTPUT][POOL2_NBOUTPUT][POOL2_HEIGHT][POOL2_WIDTH];
extern float FC1_BIAS[FC1_NBOUTPUT];
extern float FC2_KERNEL[FC2_NBOUTPUT][FC1_NBOUTPUT];
extern float FC2_BIAS[FC2_NBOUTPUT];
extern float FC2_OUTPUT[FC2_NBOUTPUT];
extern float SOFTMAX_OUTPUT[FC2_NBOUTPUT];

#endif